# Generated by Django 5.0.2 on 2024-02-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemanager',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
